version: '3.3'
# created from https://neo4j.com/developer/docker-run-neo4j/
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/test
    volumes:
      - data:/data
      - logs:/logs
      - import:/var/lib/neo4j/import
      - plugins:/plugins
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    networks:
      - private_net

volumes:
  # will be <service_name>_data
  data:
    driver: local
  logs:
    driver: local
  import:
    driver: local
  plugins:
    driver: local

# the actual name will be <directory_name>_<network_name>
networks:
  private_net:
    driver: bridge
