#!/bin/bash
#from https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-quickstart-containers-linux

# Variables
source azure-variables.sh

# pem file name is autogenerated from certificate subject name
echo "binding to cluster endpoint https://$ClusterName.$Location.cloudapp.azure.com:19080"
sfctl cluster select --endpoint https://$ClusterName.$Location.cloudapp.azure.com:19080 --pem ${ClusterName}${Location}cloudappazurecom.pem --no-verify

# weird but I had to add --debug to get this to work 4/2020
echo "un-deploying docker image to $ClusterName-test on url http://$ClusterName.$Location.cloudapp.azure.com"
sfctl compose remove --deployment-name $ClusterName-test --debug
