version: '3.3'
# created from https://neo4j.com/developer/docker-run-neo4j/
services:
  # configdb only required if instance is config server for sharded cluster
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodb_db:/data/db
      - mongodb_configdb:/data/configdb
    ports:
      - 27017:27017
    networks:
      - private_net

  mongoexp:
    image: mongo-express:latest
    container_name: mongoexp
    ports:
      - "8081:8081"
    links:
      - mongo
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - private_net

volumes:
  # will be <svc_name>_db
  mongodb_db:
    driver: local
  # will be <svc_name>_configdb
  mongodb_configdb:
    driver: local

# the actual name will be <directory_name>_<network_name>
networks:
  private_net:
    driver: bridge
