version: '3.3'
# created from https://hub.docker.com/r/tensorflow/tensorflow/
services:
  tensorflow:
    image: tensorflow/tensorflow:latest-py3-jupyter
    container_name: tensorflow-py3-jupyter
    volumes:
      - data:/tf/notebooks
      #- ${HOME}:/tf/home
    ports:
      - 8888:8888
    networks:
      - private_net

volumes:
  # will be <service_name>_data_1
  data:
    driver: local

# the actual name will be <directory_name>_<network_name>
networks:
  private_net:
    driver: bridge
