version: '3.3'
# created from https://hub.docker.com/r/tensorflow/tensorflow/
services:
  tensorflow:
    image: tensorflow/tensorflow:latest-py3-jupyter
    container_name: tensorflow-py3-jupyter
    volumes:
      - tensorflow_data:/tf/notebooks
      # comment this out if you don't want to mount GitHub inside container
      - ${HOME}/Documents/GitHub:/tf/GitHub
    ports:
      - 8888:8888
    networks:
      - private_net

volumes:
  # will be <service_name>_data_1
  tensorflow_data:
    driver: local

# the actual name will be <directory_name>_<network_name>
networks:
  private_net:
    driver: bridge
